export const appAction = {
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
  SET_IS_SEARCH: "SET_IS_SEARCH",
  SET_DISPLAY_SEARCH: "SET_DISPLAY_SEARCH",
  SET_IS_FOCUS: "SET_IS_FOCUS",
  SET_ADD_DATA_SEARCH: "SET_ADD_DATA_SEARCH",
  SET_DELETE_DATA_SEARCH: "SET_DELETE_DATA_SEARCH",
};
